Repository annuaire-entreprises-data-gouv-fr/site, pull requests merged in 2023-11, with the labels that each got.

#725 Table of Content in definition page
  components-ui/summary/index.tsx
  components/markdown/RenderMarkdownServerOnly.tsx
  components/markdown/index.ts
  components/markdown/parse-markdown.ts
  components/search-results/results-not-enough-params.tsx
  frontend/style/globals.css
  models/administrations/types.ts
  models/article/definitions/index.ts
  models/article/faq/index.ts
  models/article/type.ts
  models/definitions/index.ts
  models/historique-modifications/index.ts
  package-lock.json
  package.json
  pages/administration/[slug].tsx
  pages/definitions/[slug].tsx
  pages/definitions/index.tsx
  pages/faq/[slug].tsx
  pages/faq/index.tsx
  pages/faq/parcours.tsx
  pages/historique-des-modifications.tsx
  pages/lp/[slug].tsx
  tsconfig.tsbuildinfo
  utils/static-pages/load-all.ts
Labels: SEO

#753 Fix OG image in twitter
  components/meta/index.tsx
Labels: SEO

#770 fix: google bot (and other good bots seems to go undetected)
  pages/dirigeants/[slug].tsx
  pages/divers/[slug].tsx
  pages/donnees-financieres/[slug].tsx
  pages/elus/[slug].tsx
  pages/entreprise/[slug].tsx
  pages/espace-agent/[slug].tsx
  pages/etablissement/[slug].tsx
  pages/rechercher/carte.tsx
  utils/server-side-props-helper/extract-params-from-context.ts
  utils/server-side-props-helper/post-server-side-props.ts
  utils/user-agent/index.tsx
Labels: bug

#775 feat: use info rather than warning in data section loader
  components/section/data-section-loader.tsx
Labels: enhancement

#786 fix: throw exception to avoid caching an empty stats page
  .env.dev
  .github/workflows/pre-merge.yml
  clients/matomo/index.ts
Labels: bug
