Repository annuaire-entreprises-data-gouv-fr/site, pull requests merged in 2025-05, with the labels that each got.

#1766 [Grist]chore: udpate grist docId
  clients/external-tooling/grist.ts
Labels: update

#1762 feat: pagination alim confiance
  app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/alim-confiance/section.tsx
  clients/api-data-gouv/alim-confiance/index.ts
  clients/api-data-gouv/alim-confiance/interface.ts
  components/search-results/results-pagination/index.tsx
  components/search-results/results-pagination/local-pagination.tsx
  hooks/fetch/alim-confiance.ts
Labels: enhancement

#1770 fix: update spectacle vivant fields
  clients/open-data-soft/clients/entrepreneur-spectacles/index.ts
  components/labels-and-certificates/entrepreneur-spectacles/index.tsx
  cypress/fixtures/entrepreneur-spectacles.json
  models/certifications/entrepreneur-spectacles.ts
Labels: bug, update

#1771 fix: robots.txt
  app/robots.ts
  pages/erreur/acces-refuse.tsx
Labels: bug

#1776 fix: link entreprise patrimoine vivant data gouv
  data/administrations/mef.yml
Labels: bug

#1780 fix: update label handling in EtablissementTable component
  components/etablissement-liste-section/index.tsx
Labels: content

#1777 feat: multi label filter
  components/advanced-search/filter-structure.tsx
  models/search/search-filter-params.ts
Labels: enhancement

#1792 chore: update non-diffusible description
  components/non-diffusible-section/index.tsx
Labels: content

#1797 feat: add X-Robots-Tag header to share button and QR route responses
  app/api/share/button/[slug]/route.ts
  app/api/share/qr/[slug]/route.ts
Labels: seo

#1796 feat: consultant email are prestataire
  models/authentication/agent/agent-connected/index.test.ts
  models/authentication/agent/agent-connected/index.tsx
Labels: enhancement
