Repository annuaire-entreprises-data-gouv-fr/site, pull requests merged in 2025-07, with the labels that each got.

#1846 feat: sirene.fr add legal categories filter
  app/(header-default)/export-csv/ExportCsv.tsx
  app/(header-default)/export-csv/Filters.tsx
  app/(header-default)/export-csv/FiltersSummary.tsx
  app/api/export-csv/input-validation.ts
  clients/sirene-insee/build-query.ts
  components-ui/icon/index.tsx
Labels: enhancement

#1845 feat: sirene.fr add naf filter
  app/(header-default)/export-csv/ExportCsv.tsx
  app/(header-default)/export-csv/Filters.tsx
  app/(header-default)/export-csv/FiltersSummary.tsx
  app/api/export-csv/input-validation.ts
  clients/sirene-insee/build-query.ts
  scripts/nomenclature-d-activites-francaises/README.md
  scripts/nomenclature-d-activites-francaises/generateMappingNiv1ToNiv5.js
  scripts/nomenclature-d-activites-francaises/naf2008_5_niveaux.csv
  scripts/nomenclature-d-activites-francaises/niv1ToNiv5Mapping.ts
Labels: enhancement

#1847 feat: sirene.fr add siren/siret upload
  app/(header-default)/export-csv/ExportCsv.tsx
  app/(header-default)/export-csv/Filters.tsx
  app/(header-default)/export-csv/FiltersSummary.tsx
  app/(header-default)/export-csv/SiretFilter.tsx
  app/(header-default)/export-csv/styles.module.css
Labels: enhancement

#1868 [FAQ]chore: add etat administratif to faq page
  data/administrations/inpi.yml
Labels: content

#1865 feat: add permanent redirect for entreprise slug when it is a siren
  app/(header-default)/entreprise/[slug]/page.tsx
  cypress/e2e/fonctionnalites/unite-legale-pagination.cy.js
  cypress/e2e/recherche/research-redirections.cy.js
Labels: seo

#1872 chore: update to new d-roles api
  clients/api-d-roles/index.ts
  clients/routes.ts
  models/group/index.ts
  models/groups/index.ts
Labels: enhancement

#1857 [Espace-Agent]feat: ux d-roles
  app/(header-compte)/admin/page.tsx
  app/(header-compte)/mes-equipes/page.tsx
  app/(header-compte)/mon-espace/page.tsx
  app/api/groups/[groupId]/add-user/route.ts
  app/api/groups/[groupId]/remove-user/route.ts
  app/api/groups/[groupId]/update-name/route.ts
  app/api/groups/[groupId]/update-user/route.ts
  app/api/groups/input-validation.ts
  app/api/groups/route-helpers.ts
  app/api/groups/route-wrappers.ts
  clients/api-d-roles/index.ts
  clients/api-d-roles/interface.ts
  clients/routes.ts
  components-ui/full-screen-modal/index.tsx
  components-ui/full-screen-modal/styles.module.css
  components-ui/icon/index.tsx
  components/espace-agent-components/add-user.tsx
  components/espace-agent-components/agent-navigation-link.tsx
  components/espace-agent-components/agent-navigation.tsx
  components/espace-agent-components/delete-user.tsx
  components/espace-agent-components/group-entity.tsx
  components/espace-agent-components/group-management.tsx
  components/espace-agent-components/update-name.tsx
  components/espace-agent-components/update-user.tsx
  components/header/header-core/index.tsx
  components/header/menu/index.tsx
  components/welcome-modal-agent/index.tsx
  cypress/e2e/fonctionnalites/espace-agent.cy.js
  cypress/support/commands.ts
  models/authentication/agent/agent-connected/index.test.ts
  models/authentication/agent/agent-connected/index.tsx
  models/authentication/agent/index.ts
  models/authentication/group/groups.ts
  models/authentication/group/index.ts
  models/authentication/group/roles.ts
Labels: enhancement

#1883 Fix d role front
  components-ui/full-screen-modal/index.tsx
  components/espace-agent-components/add-user.tsx
  components/espace-agent-components/group-entity.tsx
  components/espace-agent-components/group-management.tsx
  components/espace-agent-components/update-name.tsx
  components/welcome-modal-agent/index.tsx
Labels: enhancement
